# Generated by Django 5.2 on 2025-04-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('Earned', 'Earned'), ('Passive', 'Passive'), ('Portfolio', 'Portfolio'), ('Others', 'Others')], max_length=50),
        ),
    ]
