# Generated by Django 5.1.8 on 2025-04-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_income_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
